### ISSUE TITLE
Store focus points in manual BestFocusSubstack as metadata

### ISSUE THREAD

**Issue by SJCross** [SJCross/MIA#91]

**Comment by alibhaid** [comment]
![giphy (1)](https://user-images.githubusercontent.com/19326592/56953869-5d0bbd80-6b35-11e9-9dde-75648a1e6195.gif)

**Comment by SJCross** [comment]
Love the fact GitHub included gifs as an option

**Comment by SJCross** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5b484722e3a6310f00a38636/attachments/5cc81f415527c3000fa2e5bf)

**Comment by SJCross** [comment]
![giphy](https://user-images.githubusercontent.com/29373423/56955260-d062fe80-6b38-11e9-845b-bd18fdcaf780.gif)

**Comment by alibhaid** [comment]
![giphy (1)](https://user-images.githubusercontent.com/19326592/56958498-5b94c200-6b42-11e9-8dbc-506ba4484379.gif)
