### ISSUE TITLE
Implement octree structure for coordinates

### ISSUE THREAD

**Issue by SJCross** [SJCross/MIA#95]

**Comment by SJCross** [comment]
Octrees would allow large regions of identical, contiguous object pixel coordinates to be reduced to individual cubes.  Assuming this didn't result in a massive performance loss, it could massively reduce the memory required to store objects.

**Comment by alibhaid** [comment]
OCATREES FOR EVERYONE!


Dr. Dominic Alibhai | Senior Light Microscopy Technician | Wolfson Bioimaging Facility
Biomedical Sciences Building | University of Bristol, Bristol, BS8 1TD UK
Email: da14205@bristol.ac.uk<mailto:da14205@bristol.ac.uk> | W: http://www.bristol.ac.uk/wolfson-bioimaging/

________________________________
